apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-admin-ui
  labels:
    app: {{ .Release.Name }}-admin-ui
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-admin-ui
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-admin-ui
    spec:
      containers:
        - name: admin-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-admin-ui-config
            - secretRef:
                name: {{ .Release.Name }}-admin-ui-secret
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
