apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin-ui
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-admin-ui
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
